# Opciones de patrocinio para .ai-dev
# Descomenta las líneas que apliquen a tu caso

# github: [soydachi]
# patreon: username
# open_collective: ai-dev
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# lfx_crowdfunding: project-name
# polar: username
# custom: ["https://example.com/sponsor"]
